/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sePlannifMilitar;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.Cursor;
import javax.swing.JOptionPane;
/**
 *
 * @author Ariel G
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private Sonido disparo;
    private int actual, contador;
    //private boolean esCrimenOrg;
    private Cursor cur;
    private PanelSecundario panelSecun=null;
    public Main() {
        actual=0;contador=0;
        disparo=new Sonido("sonido/disparo.wav");
        //esCrimenOrg=true;
        initComponents();
        /*panelSecun=new PanelSecundario(this);
        panelSecun.setBounds(0, 60, 1000, 650);
        panelSecun.setVisible(false);
        add(panelSecun);*/
        anularFlechas();
    }
    public void setActual(int actual){this.actual=actual;}
    public void anularFlechas(){
        if(actual==0){
            btnAtras.setEnabled(false);
            if(contador>0)
                btnAdelante.setEnabled(true);
            else
                btnAdelante.setEnabled(false);
        }else if(actual>0){
            btnAtras.setEnabled(true);
            btnAdelante.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInicio = new javax.swing.JPanel();
        btnCrimen = new javax.swing.JButton();
        btnTerro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();
        setIconImage(new ImageIcon("sonido/icon.png").getImage());
        Image im = Toolkit.getDefaultToolkit().createImage("sonido/mira.png");
        cur = Toolkit.getDefaultToolkit().createCustomCursor(im, new Point(10,10),"WILL");
        toolBar = new javax.swing.JToolBar();
        btnSE = new javax.swing.JButton();
        btnUso = new javax.swing.JButton();
        btnNosotros = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        lblTipoYarea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Experto v 1.0");
        getContentPane().setLayout(null);

        PanelInicio.setLayout(null);

        btnCrimen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnCrimen1.png"))); // NOI18N
        btnCrimen.setToolTipText("");
        btnCrimen.setBorder(null);
        btnCrimen.setBorderPainted(false);
        btnCrimen.setContentAreaFilled(false);
        btnCrimen.setFocusPainted(false);
        btnCrimen.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnCrimen2.png"))); // NOI18N
        btnCrimen.setCursor(cur);
        btnCrimen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrimenActionPerformed(evt);
            }
        });
        PanelInicio.add(btnCrimen);
        btnCrimen.setBounds(30, 200, 231, 100);

        btnTerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnTerro1.png"))); // NOI18N
        btnTerro.setToolTipText("");
        btnTerro.setBorder(null);
        btnTerro.setBorderPainted(false);
        btnTerro.setContentAreaFilled(false);
        btnTerro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerro.setFocusPainted(false);
        btnTerro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnTerro2.png"))); // NOI18N
        btnTerro.setCursor(cur);
        btnTerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerroActionPerformed(evt);
            }
        });
        PanelInicio.add(btnTerro);
        btnTerro.setBounds(320, 200, 231, 100);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Cuando son un grupo (más de 1 persona) \nsocial concierta estructura y con miembros \nque se organizan para cometer acciones \ndelictivas.\nA diferencia del delincuente q actúa en \nsolitario, los individuos que forman parte \nde una banda de delincuencia organizada \ndeben responder a la estructura y cumplir \nuna determinada función. \nTareas más complejas que robos comunes \no hurtos, realizan actividades como \ntráfico de drogas o armas, trata de blancas, \ncontrabando o falsificación.");
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuando es crimen organizado?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        PanelInicio.add(jScrollPane1);
        jScrollPane1.setBounds(10, 310, 280, 280);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Cuando es un acto intencionado que,\npor su naturaleza o su contexto, pueda \nperjudicar gravemente a un país o a una\norganización internacional tipificado \ncomo delito según el ordenamiento jurídico, \ncometido con el fin de intimidar gravemente \na una población.Obligar indebidamente a \nlos gobiernos o a una organización \ninternacional a realizar un acto o a \nabstenerse de hacerlo. O desestabilizar \ngravemente o destruir las estructuras \npolíticas fundamentales, constitucionales, \neconómicas o sociales de un país o de \nuna organización internacional.\n");
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuando se trata de terrorismo?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        PanelInicio.add(jScrollPane2);
        jScrollPane2.setBounds(300, 310, 280, 280);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoInicio2.png"))); // NOI18N
        PanelInicio.add(fondo);
        fondo.setBounds(0, 0, 1000, 650);

        getContentPane().add(PanelInicio);
        PanelInicio.setBounds(0, 60, 1000, 650);

        toolBar.setRollover(true);

        btnSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exlpliacion.png"))); // NOI18N
        btnSE.setToolTipText("que es un S.E.");
        btnSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSE.setFocusable(false);
        btnSE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEActionPerformed(evt);
            }
        });
        toolBar.add(btnSE);

        btnUso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        btnUso.setToolTipText("como usar");
        btnUso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUso.setFocusable(false);
        btnUso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsoActionPerformed(evt);
            }
        });
        toolBar.add(btnUso);

        btnNosotros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nosotros.png"))); // NOI18N
        btnNosotros.setToolTipText("acerca de nosotros");
        btnNosotros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNosotros.setFocusable(false);
        btnNosotros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNosotros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNosotrosActionPerformed(evt);
            }
        });
        toolBar.add(btnNosotros);
        toolBar.add(jSeparator1);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        btnSalir.setToolTipText("salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        toolBar.add(btnSalir);
        toolBar.add(jSeparator2);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        btnAtras.setToolTipText("atras");
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setFocusable(false);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        toolBar.add(btnAtras);

        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adelante.png"))); // NOI18N
        btnAdelante.setToolTipText("adelante");
        btnAdelante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdelante.setFocusable(false);
        btnAdelante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdelante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        toolBar.add(btnAdelante);
        toolBar.add(jSeparator3);

        lblTipoYarea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipoYarea.setText("  TIPO DE PROBLEMA: PLANIFICACION / AREA: MILITAR");
        toolBar.add(lblTipoYarea);

        getContentPane().add(toolBar);
        toolBar.setBounds(0, 0, 1000, 49);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Mensaje dentro de la ventana"
        JOptionPane.showMessageDialog(this, "Un Sistema Experto es aquel capaz de almacenar el conocimiento "
        + "de un experto\nen una especialidad determinada y limitada, y a su vez de solucionar problemas\nmediante "
        + "la inducción- deducción lógica.\nLos sistemas expertos son programas de computación que capturan el "
        + "conocimiento\nde un experto y tratan de imitar su proceso de razonamiento cuando resuelven los\n"
        + "problemas en un determinado dominio.", "Definición de S.E.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSEActionPerformed

    private void btnUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "- Primero selecione una de las opciones: CRIMEN ORGANIZADO ó TERRORISMO."
        + "\n- A continuacion vaya contestando cada una de las preguntas que saldran,\n  con esto al final el S.E."
        + " le brindara una lista de pasos que debe seguir para enfrentar\n  "
        + "el tipo de problema que previamente seleciono.\n- En caso de no aparecer las preguntas haga "
        + "click en el boton verde de reiniciar.", "Información de uso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUsoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if(resp==0)
            System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNosotrosActionPerformed
        // TODO add your handling code here:
        MyIconPersonalizado icon = new MyIconPersonalizado(85,185,"/images/logos.png");
        JOptionPane.showMessageDialog(null, "FACULTAD DE CIENCIAS Y TECNOLOGIA\nUNIVERSIDAD MAYOR DE SAN SIMON"
        + "\nCochabamba - Bolivia"
        + "\n\nIntegrantes:     Bustos Pozo Deysi"
        + "\n                          Galvez Ponce Ariel"
        + "\n                          Sausiri Canaviri Hernan"
        + "\n                          Villazon Delgado Gabriel\n"
        + "\nCarrera:           Ingenieria de Sistemas\n"
        + "\nMateria:           Sistemas Expertos\n"
        + "\nDocente:           Lic. Garcia Perez Carmen Rosa\n"
        + "\nGestión:           II - 2015\n", "Acerca de nosotros", JOptionPane.DEFAULT_OPTION, icon);   
    }//GEN-LAST:event_btnNosotrosActionPerformed

    private void btnCrimenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrimenActionPerformed
        // TODO add your handling code here:
        reproducirSonido();
        crearPanel(true);
        actual=1;
        anularFlechas();
        PanelInicio.setVisible(false);
        panelSecun.cambiarCaso(true);
        panelSecun.setVisible(true);
        panelSecun.iniciarMotorDeInferencia();
    }//GEN-LAST:event_btnCrimenActionPerformed

    private void btnTerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerroActionPerformed
        // TODO add your handling code here:
        reproducirSonido();
        crearPanel(false);
        actual=2;
        anularFlechas();
        PanelInicio.setVisible(false);
        panelSecun.cambiarCaso(false);
        panelSecun.setVisible(true);
        panelSecun.iniciarMotorDeInferencia();
        
    }//GEN-LAST:event_btnTerroActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        actual=0;
        contador++;
        anularFlechas();
        panelSecun.setVisible(false);
        PanelInicio.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // TODO add your handling code here:
        actual=1;
        contador++;
        anularFlechas();
        PanelInicio.setVisible(false);
        panelSecun.setVisible(true);
    }//GEN-LAST:event_btnAdelanteActionPerformed
    public void crearPanel(boolean esCrimen){
        panelSecun=new PanelSecundario(this,esCrimen);
        panelSecun.setBounds(0, 60, 1100, 650);
        panelSecun.setVisible(false);
        add(panelSecun);
        anularFlechas();
    }
    public void reproducirSonido(){
        disparo.reproducir();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {//RavenGraphiteGlassSkin este es negro
                org.jvnet.substance.SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenGraphiteGlassSkin");//MistAquaSkin GreenMagicSkin NebulaSkin
                Main m=new Main();
                m.setSize(1010, 730);
                m.setLocationRelativeTo(null);
                //m.setResizable(false);
                m.setVisible(true);
                }catch (Exception e) {}
                
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrimen;
    private javax.swing.JButton btnNosotros;
    private javax.swing.JButton btnSE;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTerro;
    private javax.swing.JButton btnUso;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblTipoYarea;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
